### ISSUE TITLE
Sites not working

### ISSUE THREAD

**Issue by 04ssti** [FluxionNetwork/sites#4]
When I try any of the sites such as the Xfinity portal, when the user enters their password and hits submit, nothing happens and Fluxion doesn't capture the password. 
When I open up index.html in a browser and hit submit it gives me an error "can't find file "check.php"

**Comment by deltaxflux** [comment]
Have you tried other login pages ?
And how do you start the fake AP

**Comment by 04ssti** [comment]
Yeah I have tried other sites such as netgear and tp-link. All do the same, I input the password and hit submit and fluxion registers an attempt but that’s it. When I tried it with the generic English login page it works how it should. I used option 1. Hostapd for the fake AP. I haven't tried option 2 yet.
![attack-selection](https://user-images.githubusercontent.com/5479618/33869393-44386bba-debd-11e7-9bc4-095241b0f05a.png)



Thanks.

**Comment by deltaxflux** [comment]
You mess up with a old version. Please update your fluxion.

**Comment by deltaxflux** [comment]
```
cd
rm -rf fluxion

git clone --recursive https://github.com/FluxionNetwork/fluxion.git # Download the latest revision
cd fluxion # Switch to tool's directory
./fluxion.sh # Run fluxion (missing dependencies will be auto-installed)

```

**Comment by MPX4132** [comment]
Damn, 0.25 lol, when was that released? That's definitely more than a year old, right?
