### ISSUE TITLE
How to make custom one

### ISSUE THREAD

**Issue by phspade** [FluxionNetwork/sites#5]
I want to make a custom router page without the router.sh. What i really want to know is how Fluxion read or process the WPA Password.. is there any variable or what?

**Comment by deltaxflux** [comment]
Yeah there is. First check the fluxion wiki page. If there is something unclear ask me again

**Comment by MPX4132** [comment]
[Here’s the article on prepping portals for fluxion](https://github.com/FluxionNetwork/fluxion/wiki/Prepping-protals-for-fluxion), if you have more questions ask us.
